/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=research/wrangler.jsonc --include-runtime=false --env-interface=ResearchEnv research/worker-configuration.d.ts` (hash: 89f328089e8211a515af3ff9cd3d1f4c)
interface __BaseEnv_ResearchEnv {
	DB: D1Database;
	NEBIUS_MODEL: "nvidia/nemotron-3-super-120b-a12b";
	MAX_DAILY_JOBS: "3" | "10";
	MAX_ACTIVE_JOBS: "1" | "2";
	RECEPTION_FROM: "" | "reception@openwallstreet.zishenchan.com";
	NEBIUS_API_KEY: string;
	TAVILY_API_KEY: string;
	NEBIUS_JOB_SERVICE_TOKEN: string;
	RESEARCH_WORKFLOW: Workflow<Parameters<import("./index").ResearchWorkflow['run']>[0]['payload']>;
	RECEPTION_EMAIL?: SendEmail;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface PreviewEnv {
		DB: D1Database;
		NEBIUS_MODEL: "nvidia/nemotron-3-super-120b-a12b";
		MAX_DAILY_JOBS: "3";
		MAX_ACTIVE_JOBS: "1";
		RECEPTION_FROM: "";
		NEBIUS_API_KEY: string;
		TAVILY_API_KEY: string;
		NEBIUS_JOB_SERVICE_TOKEN: string;
		RESEARCH_WORKFLOW: Workflow<Parameters<import("./index").ResearchWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_ResearchEnv {}
}
interface ResearchEnv extends __BaseEnv_ResearchEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEBIUS_MODEL" | "MAX_DAILY_JOBS" | "MAX_ACTIVE_JOBS" | "RECEPTION_FROM" | "NEBIUS_API_KEY" | "TAVILY_API_KEY" | "NEBIUS_JOB_SERVICE_TOKEN">> {}
}
